#version: '3.8'
services:
  db_development:
    image: mysql:latest
    volumes:
      - mysql-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: EventManager_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # 3307 is the host port, 3306 is the container port
    restart: always
  
  db_test:
    image: mysql:latest
    volumes:
      - mysql-data-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: EventManager_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"  
    restart: always

  web:
    build: .
    env_file:
      - .env.container
    command: >
      bash -c "rm -f tmp/pids/server.pid && rails db:prepare && rails db:seed && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp # mount the current directory to /myapp in the container
    ports:
      - "3010:3000" #la porta del container 3000 viene mappata sulla porta del host 3010
    depends_on: # start after the db containers are up
      - db_development
      - db_test
    restart: always

volumes:
  mysql-data-dev:
  mysql-data-test:
