# Mysql for the database
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['HOST'] %>

development:
  <<: *default
  database: EventManager_development
  host: <%= ENV['HOST_DEVELOPMENT'] %>

test:
  <<: *default
  database: EventManager_test
  host: <%= ENV['HOST_TEST'] %>


