name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Using the secret here
          MYSQL_USER: ${{ secrets.DB_USERNAME }}  # Using the secret here
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Using the secret here
          MYSQL_DATABASE: db_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3  # Ensure this matches the Ruby version you want to use
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev
        bundle install

    - name: Start MySQL
      run: |
        sudo service mysql start

    - name: Print Environment Info
      run: |
        echo "MYSQL_USER=$MYSQL_USER"
        echo "MYSQL_PASSWORD=$MYSQL_PASSWORD"
        echo "HOST_TEST=$HOST_TEST"



    - name: Run Tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec
