name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      
      services:
        mysql:
          image: mysql:latest
          env:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: EventManager_test
          ports:
            - 3306:3306
          volumes:
            - mysql-data-test:/var/lib/mysql
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=10s
            --health-retries=10
  
      steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Install dependencies
        run: |
          sudo apt-get install libmysqlclient-dev
          bundle install

      - name: Start the sql server
        run: |

          bundle exec rake db:prepare

      - name: Setup Database Config
        run: |
            echo "MYSQL_PASSWORD=password" >> $GITHUB_ENV
            echo "HOST=mysql" >> $GITHUB_ENV
            echo "RAILS_ENV=test" >> $GITHUB_ENV
        
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec