name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: EventManager_test
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libpq-dev nodejs
        gem install bundler
        bundle install

    - name: Install netcat
      run: sudo apt-get install -y netcat

    - name: Test MySQL Service
      run: |
        mysql -h db -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"
    
      
  

    - name: Run tests
      run: |
        bundle exec rspec
