name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: EventManager_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3315:3306

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libpq-dev nodejs
        gem install bundler
        bundle install
  
    
    - name: Run tests
      run: |
        bundle exec rspec
