name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      
      services:
        mysql:
          image: mysql:lastest
          env:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: EventManager_test
          ports:
            - 3306:3306
          options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=10s
            --health-retries=10
  
      steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3  # Specify your Ruby version
      - name: Install dependencies
        run: |
          sudo apt-get install libmysqlclient-dev
          bundle install
      - name: Setup Database
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          HOST_TEST: 127.0.0.1
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec