name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mysql_test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
    steps:
    - name: Check MySQL
      run: |
        sleep 10
        mysql -h db -uroot -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"